# Generated by Django 4.1.5 on 2023-01-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
