# Generated by Django 4.1.5 on 2023-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0002_anime_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='imdbRating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='malRating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='myRating',
            field=models.FloatField(null=True),
        ),
    ]
